INSERT INTO series (title, author_id, subgenre_id) VALUES ("Hitchhikers Guide", 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("The Culture", 2, 1);
INSERT INTO books (title, year, series_id) VALUES ("Hitchhikers Guide to the Galaxy", 1979, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Restaurant at the End of the Universe", 1980, 1);
INSERT INTO books (title, year, series_id) VALUES ("Life, the Universe and Everything", 1982, 1);
INSERT INTO books (title, year, series_id) VALUES ("So Long, and Thanks for All the Fish", 1984, 1);
INSERT INTO books (title, year, series_id) VALUES ("Mostly Harmless", 1992, 1);
INSERT INTO books (title, year, series_id) VALUES ("Starship Titanic", 1997, 1);
INSERT INTO books (title, year, series_id) VALUES ("And Another Thing...", 2009, 1);
INSERT INTO books (title, year, series_id) VALUES ("Consider Phlebas", 1987, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Player of Games", 1988, 2);
INSERT INTO books (title, year, series_id) VALUES ("Use of Weapons", 1990, 2);
INSERT INTO books (title, year, series_id) VALUES ("The State of the Art", 1991, 2);
INSERT INTO books (title, year, series_id) VALUES ("Excession", 1996, 2);
INSERT INTO books (title, year, series_id) VALUES ("Inversions", 1998, 2);
INSERT INTO books (title, year, series_id) VALUES ("Lock to Windward", 2000, 2);
INSERT INTO books (title, year, series_id) VALUES ("Matter", 2008, 2);
INSERT INTO books (title, year, series_id) VALUES ("Surface Detail", 2010, 2);
INSERT INTO books (title, year, series_id) VALUES ("The Hydrogen Sonata", 2012, 2);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Arthur Dent", "Human", "It's at times like this, when I'm trapped in a Vogon airlock with a man from Betelgeuse, and about to die of asphyxiation in deep space that I really wish I'd listened to what my mother told me when I was young.", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Ford Prefect", "Human", "Six pints of bitter, said Ford Prefect. And quickly please, the world's about to end..", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Zaphod Beeblebrox", "Human", "I'm awesome", 2, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Deep Thought", "Computer", "42", 3, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Jernau Morat Gurgeh", "Human", "I am going to win this game that I am playing!", 1, 2);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Mawhrin-Skel", "Human", "Everyone is a silly head.", 1, 2);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Flere-Imsaho", "Human", "When I was young...", 1, 2);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Just Read the Instructions", "Spaceship", "Beebop Booop!", 1, 2);
INSERT INTO subgenres (name) VALUES ("Science Fiction");
INSERT INTO subgenres (name) VALUES ("Non Fiction");
INSERT INTO authors (name) VALUES ("Douglas Adams");
INSERT INTO authors (name) VALUES ("Ian Banks");
INSERT INTO character_books (book_id, character_id) VALUES (1, 1);
INSERT INTO character_books (book_id, character_id) VALUES (1, 2);
INSERT INTO character_books (book_id, character_id) VALUES (1, 3);
INSERT INTO character_books (book_id, character_id) VALUES (1, 4);
INSERT INTO character_books (book_id, character_id) VALUES (2, 1);
INSERT INTO character_books (book_id, character_id) VALUES (3, 2);
INSERT INTO character_books (book_id, character_id) VALUES (4, 3);
INSERT INTO character_books (book_id, character_id) VALUES (5, 1);
INSERT INTO character_books (book_id, character_id) VALUES (6, 4);
INSERT INTO character_books (book_id, character_id) VALUES (7, 1);
INSERT INTO character_books (book_id, character_id) VALUES (8, 5);
INSERT INTO character_books (book_id, character_id) VALUES (9, 5);
INSERT INTO character_books (book_id, character_id) VALUES (10, 6);
INSERT INTO character_books (book_id, character_id) VALUES (11, 7);
INSERT INTO character_books (book_id, character_id) VALUES (12, 8);
INSERT INTO character_books (book_id, character_id) VALUES (13, 5);
